version: '3.8'

services:
  pg-admin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin4-personal-solo
    restart: 'no'
    environment:
      PGADMIN_DEFAULT_EMAIL: $PGADMIN_DEFAULT_EMAIL
      PGADMIN_DEFAULT_PASSWORD: $PGADMIN_DEFAULT_PASSWORD
    ports:
      - 5533:80
