version: '3.8'

services:
  pg-db:
    image: postgres:latest
    container_name: postgres-personal
    restart: always
    environment:
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
      POSTGRES_USER: $POSTGRES_USER
    ports:
      - 5430:5432
    volumes:
      - ./data:/var/lib/postgresql/data

  pg-admin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin4-personal
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: $PGADMIN_DEFAULT_EMAIL
      PGADMIN_DEFAULT_PASSWORD: $PGADMIN_DEFAULT_PASSWORD
    ports:
      - 5431:80
    depends_on:
      - pg_db
