version: '3.8'

services:
  azurite:
    image: mcr.microsoft.com/azure-storage/azurite:3.15.0
    container_name: azurite
    restart: 'no'
    environment: {}
    ports:
      - 10000:10000
      - 10001:10001
      - 10002:10002
    volumes:
      - ./data:/data
    command: "azurite --loose --skipApiVersionCheck --queueHost 0.0.0.0 --blobHost 0.0.0.0 --tableHost 0.0.0.0"
