version: '3.8'

services:
  azurite:
    image: mcr.microsoft.com/azure-storage/azurite:3.13.1
    container_name: azurite
    restart: always
    environment: {}
    ports:
      - 10000:10000
      - 10001:10001
    volumes:
      - ./data:/data
    command: "azurite --loose --skipApiVersionCheck --queueHost 0.0.0.0 --blobHost 0.0.0.0"
