version: '3.8'

services:
  azurite:
    image: mcr.microsoft.com/azure-storage/azurite:latest
    container_name: azurite
    restart: always
    environment: {}
    ports:
      - 10000:10000
      - 10001:10001
    volumes:
      - ./data:/data
